spring:
    application:
        name: identity-service
    profiles:
        active: dev
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - email
                            - profile

server:
    port: ${PORT:8080}

security:
    jwt:
        secret: ${JWT_SECRET:myVeryStrongSecretKeyForDevelopmentOnly12345}
        expiration: 3600000
        refresh-token-expiration: 604800
        access-token-expiration: 900000

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
