spring:
    application:
        name: identity-service
    profiles:
        active: dev
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - email
                            - profile

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_ID}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
app:
    verification:
        token-validity-minutes: 60  # 1 hour
    backend-base-url: http://localhost:8080

server:
    port: ${PORT:8080}

security:
    jwt:
        secret: ${JWT_SECRET:myVeryStrongSecretKeyForDevelopmentOnly12345}
        expiration: 3600000
        refresh-token-expiration: 604800
        access-token-expiration: 900000

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
    endpoint:
        health:
            probes:
                enabled: true
            show-details: when_authorized
    info:
        env:
            enabled: true

info:
    app:
        name: identity-service
        description: Identity & Authentication Service
        version: 1.0.0
